# Generated by Django 4.2.7 on 2024-12-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_trainingprogram_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
