# Generated by Django 4.2.7 on 2024-12-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_trainingprogram_trainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='is_active',
        ),
        migrations.AddField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
