# Generated by Django 4.2.7 on 2024-12-11 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_remove_membership_is_active_membership_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='gym.trainingprogram'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['user', 'program', 'status'], name='gym_members_user_id_d162a4_idx'),
        ),
    ]
