# Generated by Django 4.2.7 on 2024-12-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0009_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, help_text='Post Text'),
        ),
    ]
