# Generated by Django 4.2.7 on 2024-12-18 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0010_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
