# Generated by Django 4.2.7 on 2026-02-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0011_remove_post_image_post_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainer",
            name="photo_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="trainer",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="trainers/"),
        ),
    ]
