# Generated by Django 4.2.7 on 2026-06-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0012_trainer_photo_url_alter_trainer_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="community_posts/"
            ),
        ),
    ]
