# Generated by Django 4.2.7 on 2026-06-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0013_post_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="image",
        ),
        migrations.RemoveField(
            model_name="post",
            name="image_url",
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(help_text="Post Text"),
        ),
    ]
